version: "3.7"

services:
  prod:
    # service 1 container name
    container_name: palcoll-prod
    image: docker-react-i
    build:
      context: .
    ports:
      - "90:80"
    restart: always
    
      
